### ISSUE TITLE
some assets still deleted from excluded folder

### ISSUE THREAD

**Issue by laggyluk** [ashe23/ProjectCleaner#12]
I got project singleton set to blueprint deriving from c++ class, it got deleted despite of being directly in excluded folder (actually also some other blueprints got deleted residing in sub folders, should sub folders be added separately?)

**Comment by ashe23** [comment]
Yes, subfolders are taking to account, and working for regular assets, but I spotted a bug with assets that are based on code ( in our case BP derived from c++).
I will fix it with version 1.4 that will come soon. 

Thanks for response :)

**Comment by laggyluk** [comment]
4.26 great plugin btw, should be built-in ;)

**Comment by ashe23** [comment]
Fixed with v1.4
