### ISSUE TITLE
Tree view for Unused Assets tab

### ISSUE THREAD

**Issue by Zeblote** [ashe23/ProjectCleaner#18]
Great plugin! This the first one of these kind of plugins that I found to actually work properly (doesn't mark primary assets, assets used by C++, etc).

Currently you get all the assets sorted by name, which is a great start, but it can be difficult to investigate which groups of assets you want to keep and which not.

When you have a large amount of unused assets in the project, it would be very useful if the Unused Assets tab had a tree view for the directories they're in. Then you could very quickly drill down which folders are useless and which ones are known to still be needed for some thing in the future, or quickly isolate folders that aren't related to your work and you're not sure about.

**Comment by ashe23** [comment]
For large amount of assets , i was thinking about adding pagination or something like that, but Tree view is good suggestion.
