### ISSUE TITLE
Scrolling the Unused Assets view doesn't work properly

### ISSUE THREAD

**Issue by Zeblote** [ashe23/ProjectCleaner#19]
For some reason, I can only scroll the Unused Assets view with the mouse wheel while the cursor is above the scroll bar. It doesn't do anything while the cursor is above one of the assets. Holding right mouse and dragging (the universal quick scroll gesture in Unreal) doesn't do anything either.

**Comment by Zeblote** [comment]
Interestingly, after I moved the separator between the two main panels, scrolling with mouse wheel now works fine anywhere. But right click drag scroll is still not working. It always acts like it's at the end, doing the springy overscroll thing.

**Comment by ashe23** [comment]
Weird. I tested 2 weeks ago , seems to work properly. Maybe missed something.
Thanks anyways

**Comment by ashe23** [comment]
Does it happen only in Unused assets Tab, or in Excluded and Linked Tabs also?

**Comment by Zeblote** [comment]
The other 2 tabs don't have enough entries for me to see if it happens there. This definitely reproduces every time for me - if I open the editor now and try to scroll the unused assets tab, nothing happen.
