### ISSUE TITLE
Blueprint based primary assets are considered unused in version 1.5

### ISSUE THREAD

**Issue by Zeblote** [ashe23/ProjectCleaner#22]
Really nice update with the tree view! However there seems to be a regression, all our blueprints that are primary assets and the assets used by them are now listed as unused.

**Comment by ashe23** [comment]
Thanks for report.
It was ok on previous version (1.4) ?

**Comment by Zeblote** [comment]
Yeah, it worked fine in 1.4.

**Comment by Zeblote** [comment]
By blueprint based primary assets I mean ones that have a C++ base class, are registered like this

`+PrimaryAssetTypesToScan=(PrimaryAssetType="BRPickupBase",AssetBaseClass=/Script/Brickadia.BRPickupBase,bHasBlueprintClasses=True,Directories=((Path="/Game/Pickups")),Rules=(CookRule=AlwaysCook))`

And have blueprints derived from them in the folder.

**Comment by ashe23** [comment]
Got it.
I ll check it out

**Comment by ashe23** [comment]
Fixed issue. You can try out now.
Also added support for 4.27, but still need to wait for marketplace to update :(

**Comment by Zeblote** [comment]
Thanks, it works again.
