### ISSUE TITLE
"Failed to delete some assets"

### ISSUE THREAD

**Issue by MarioMarietto** [ashe23/ProjectCleaner#28]
Hey there!
I've installed this plugin a few days ago, but since I've installed it I keep getting: "Failed to delete some assets". (it's actually not deleting any assets at all).
I've tried redownloading and reinstalling the plugin but it didn't help. I'm using Unreal Engine 5.
Any help is appreciated, thanks! :)

**Comment by MarioMarietto** [comment]
Oh and I have Source Control disabled (I just saw #26)

**Comment by ashe23** [comment]
Hi
Some output log when this error occurring would be very helpful :)

**Comment by MarioMarietto** [comment]
It was an issue with just one asset! Looking at the Output Log I found that I had an error saying that one asset could not be found. I deleted the asset that required this other "missing" asset and it's working now!
Awesome plugin btw!
Thanks a lot and have a great day!
