### ISSUE TITLE
Feature, Export unused files to blacklist txt

### ISSUE THREAD

**Issue by imtrobin** [ashe23/ProjectCleaner#29]
Hi, UE4 has feature to blacklist files when packaging. Instead of deleting from project, can u export the unused files to PakBlacklist-xxx.txt  to use for packaging instead of deleting from source project.

**Comment by ashe23** [comment]
Hi
Well my initial thoughts was to clean everything, that you are not using and keep overall project size small. But I guess its a good suggestion and can be as additional option. Maybe not adding whole list of assets to blacklist file, but instead make something similar to Recycle Bin? Create seperate folder in projects root dir, and move all assets there and exclude that directory from packaging.

**Comment by ashe23** [comment]
Also where do you expect that txt file must be?
I am thinking in `Saved` folder, so it wont conflict with anything. Later you can just copy paste it in `Build/Platform/(Target Platform Folder)`.

**Comment by imtrobin** [comment]
I tested, there are different blacklist files for dev/shipping/platform, so that might be easier for us to copy it manually. I think Saved folder is good.

**Comment by ashe23** [comment]
HI @imtrobin 
Your functionality will be available in v1.6.0, I am working on it right now. I think in a couple of days max 1 week, it will be available :)
Testing for all versions (4.25 - 5.0.0) takes a bit time.

So back to your case. I wont add any new buttons in UI , BUT I exposed all Plugin API to Blueprints. So it will be easy for you do with data whatever you need. More on that after release.

Also I researched a bit about `PakBlacklists.txt` files and turn out , its kinda deprecated feature already.
Here is links for more information about that.
[Link1](https://forums.unrealengine.com/t/pak-blacklist-file-deprecated-in-favor-of-defaultpakfilerules-ini/153080)  
[Link2](https://qiita.com/kotarotaro_A/items/a6892e0c305c6a40d06c) (this one in Japanese, but google chrome will help :) )

**Comment by ashe23** [comment]
API exposed to Blueprints now.  (Check Release v.1.6.0)
You can now export results to file.
To use it you can create `Editor Utility Widget` and in there create UI you like and connect to ProjectCleaner logic.
Here some example  
![s1](https://user-images.githubusercontent.com/8270558/149627366-f2b0fba9-fa39-41e7-91d7-9365a9eb9021.png)

Then it creates file in `Saved/ProjectCleaner` directory.
