### ISSUE TITLE
UE5 Preview Problem

### ISSUE THREAD

**Issue by NequZ** [ashe23/ProjectCleaner#33]
Hey, i cant open a Project in UE5 Preview

https://i.imgur.com/ih7m16c.png

**Comment by ashe23** [comment]
Hi, yes `Preview` version just got released,  so I will try to update plugin as soon as possible

**Comment by ashe23** [comment]
Hey @NequZ 
Version for ue5 preview updated and available in releases to download.
I guess engine made changes in content browser by adding `Show All Folder` option, in order for engine to work properly it must be disabled.
![Screenshot 2022-02-24 055053](https://user-images.githubusercontent.com/8270558/155442841-2dba2b56-c2c4-400a-9a29-af20e5ed4620.png)

Write now I am disabling that option automatically when you opening `ProjectCleaner` window, but in some point if you cant see assets in `UnunsedAssets` or `ExcludedAssets` tabs, remember about this option :)
