### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by ahrbe1** [ashe23/ProjectCleaner#38]
I've implemented compilation fixes for building under Linux against 5.0.2. It's all pretty much minor stuff. Clang v10 appears to be more strict than the Visual Studio compiler. 

Have a look at https://github.com/ahrbe1/ProjectCleaner/commit/c5c5bdbfc793c9037914853760147443782aa4e2 

Two functions appear to be deprecated and resulted in warnings, so I updated those using the recommended APIs. Though that part may need to be checked against 4.2.x to ensure it still compiles. Those functions are `GetAssetPackageDataCopy()` and `GetCachedEmptyPackagesCopy()`. They aren't strictly necessary for the Linux build, though. 

I can open a PR if desired.

**Comment by ashe23** [comment]
Well it would be nice if you create PR :) Until then I will test plugin for 4.x versions.
Can you give more info on your Linux environment (OS, compiler) ? As far as I know, UE5 have some problems working on latest builds. (ubuntu 21+) .

**Comment by ahrbe1** [comment]
I have Ubuntu 20.04 LTS. The SDK they provide on the Linux UE 5.x branch has v20_clang-13.0.1-centos7, which I believe is part of a pre-compiled toolchain. I thought it was Clang 10, but it looks like it's actually Clang 13.

**Comment by ashe23** [comment]
I created new version with linux support. Also in order to be not confused about branches, I renamed `master` => `4.27`. So you might need to update your local repo. I would really appreciate if you test new version on your machine :) 
I will update new version on marketplace also if everything ok. 

PS. Thanks for contribution 👍

**Comment by ahrbe1** [comment]
Working on testing this tonight. 

I do have one question. Which may not be related to this patch, but it popped up in testing, so I'll mention it. 

Is there any reason that a "Refresh" would delete files from my working copy? On refresh (and initial window load), something deletes the following two files from my tree automatically. I'm trying to track it down. I looked at all instances of `DeleteFile()` in the plugin, and put in some logging, but nothing stuck out to me as what might cause this.  

```
$ svn stat | grep \!
!       Content/FirstPerson/Blueprints/BP_FirstPersonGameMode.uasset
!       Content/FirstPerson/Maps/FirstPersonMap.umap
```

Subsequently, ProjectCleaner reports a bunch of files as Corrupted, which I suspect might be related. If I `svn revert` the assets, and re-run the Refresh, the above two files are deleted again. At the very least, I don't understand the behavior. 

Here's an example of something that the plugin says is corrupted:

```
/Game/__ExternalObjects__/StarterContent/FirstPerson/Maps/FirstPersonMap/0/J6/J3LYMVPM91PMOWAAX8WTE7.J3LYMVPM91PMOWAAX8WTE7
```

Which looks like it maps to

```
./Content/__ExternalObjects__/StarterContent/FirstPerson/Maps/FirstPersonMap/0/J6/J3LYMVPM91PMOWAAX8WTE7.uasset
```

**Comment by ahrbe1** [comment]
So I forced UE to segfault if it tries to delete one of those files. I got a stack trace, and it looks like the delete happens from some function indirectly called by `FixupRedirectors()`. Relevant call stack (innermost frame on top):

```
ObjectTools::DeleteObjectsUnchecked
FAssetDeleteModel::DoDelete
ObjectTools::DeleteObjects
FAssetFixUpRedirectors::DeleteRedirectors
FAssetFixUpRedirectors::ExecuteFixUp
FAssetFixUpRedirectors::FixupReferencers
FProjectCleanerDataManager::FixupRedirectors
FProjectCleanerDataManager::AnalyzeProject
```

I dont think that's related to this patch. The test project I'm using seems to not pass the fixup routine.

**Comment by ashe23** [comment]
Well when you hit `Refresh`, before scanning its fixup all redirectors in `/Game` folder , to ensure every assets and their references/dependencies can be scanned and deleted correctly. 

When I migrated to `ue5` I got this kind of weird bugs as you shown too. Note that `ProjectCleaner` not even installed.
- I created simple empty map
- imported some `static meshes`  and added to map
- then moved  `static meshes` location in content browser
- saved the map
- and Voila , when I `Fixing UP` redirectors its just keep removing those assets, same situation as yours
 
I dig into codes a bit, seems like its related to this new features [OFPA](https://docs.unrealengine.com/5.0/en-US/one-file-per-actor-in-unreal-engine/#:~:text=One%20File%20Per%20Actor%20(OFPA,only%20available%20in%20the%20Editor.) and `World Partition` and how they handle object serializations, and store cached assets, but not 100% sure. 

Honestly, `FixUp redirectors` stuff is just a big `HACK` that sneaks to latest engine versions and its not fixed yet. I dont know why they not changing it. Its just very essential and important thing. I encountered so many times with this kind of problems in projects, where people just importing bunch of stuff moving things around and forgetting to `fixup redirectors`, and then suddenly you cant normally open project or some stuff missing in map, or in content browser 😒  That`s why I`m still using `4.27` for production, `UE5` looks amazing , no comment, but its just still raw and this kind of bugs makes it unusable sometimes.

**Comment by ahrbe1** [comment]
Makes sense. Yeah, my experience with UE5 is that it is pretty raw as well. I'm currently evaluating if it's usable for my project or if I should use 4.x.

But anyways, the plugin runs just fine on Linux / UE5, despite the current set of UE5 quirks.

**Comment by ashe23** [comment]
All right. I also tested on 4.x versions, did not have any problem what so ever. So I will close this issue and update on marketplace too.

Thanks!
