### ISSUE TITLE
UE 5.0.3 support 

### ISSUE THREAD

**Issue by Ha1uk** [ashe23/ProjectCleaner#40]
I installed the plugin for newly released 5.0.3, it causes an error and prevents opening the project. The update might've broke something in the plugin.

**Comment by ashe23** [comment]
Can you please specify in detail what kind of error it causing? Some logs would be nice :)
Because I tested v5.0.3 on my projects, and its working fine.

**Comment by Ha1uk** [comment]
I'm getting this message:

![image](https://user-images.githubusercontent.com/93527799/179453534-06456c49-addb-40ad-8b3d-1461c5bb0f6a.png)
