### ISSUE TITLE
update plugin for engine v5.1

### ISSUE THREAD

**Issue by ashe23** [ashe23/ProjectCleaner#43]

**Comment by AngelAvellaneda** [comment]
Hello Ashot, what's up, I'm looking forward to seeing the update to 5.1, I hope you're not having too many problems updating it, greetings

**Comment by ashe23** [comment]
Hi @AngelAvellaneda
No problems, still working on it , just got a bit busy lately. 
I am making couple of user interface updates, so it will take some time, but I will try to finish as soon as possible.

**Comment by AngelAvellaneda** [comment]
Great to hear that you are making great improvements, take the time you need and thank you very much for everything
