### ISSUE TITLE
Can't use it, clicking "Scan Project" gives an error.

### ISSUE THREAD

**Issue by songjinxi** [ashe23/ProjectCleaner#48]
Can't use it, clicking "Scan Project" gives an error.
![image](https://github.com/ashe23/ProjectCleaner/assets/10181820/39e87d2a-4b65-4853-9550-6990bfae9c07)
![image](https://github.com/ashe23/ProjectCleaner/assets/10181820/3198099c-8d0d-4796-894f-d37285755ae4)

**Comment by ashe23** [comment]
Hello
Well its seems you have unresolved [redirectors](https://dev.epicgames.com/documentation/en-us/unreal-engine/asset-redirectors-in-unreal-engine) in project ,which plugin cant fix automatically.
You should fix them manually, by right clicking on `Content` folder and click Fixup Redirectors

![Screenshot 2024-04-15 103126](https://github.com/ashe23/ProjectCleaner/assets/8270558/7f3b5d52-f64d-49f6-9b46-4d5cf70e8966)

Than look in OutputLog which assets are causing this issue. There can be situation where only solution will be to delete that asset and reimport it. After fixing those everything will work as expected.

PS. There is some bug in unreal engine 5.2+ feature packs, that can cause this also, here is [video](https://youtu.be/SPNSjM1iSGA) demo.

Let me know if you need any further assistance.

**Comment by songjinxi** [comment]
It's because of the "unreal engine 5.3+ feature packs, first person examples", after deleting it, the plugin works fine.

**Comment by ashe23** [comment]
Glad it worked.
