### ISSUE TITLE
keeps saying that not all Redirectories are fixed

### ISSUE THREAD

**Issue by ehab2001** [ashe23/ProjectCleaner#51]
I get a message saying "failed to scan the project because not all Redirectories are fixed but I've fixed up Redirectories on the main content folder already, I tried reinstalling the plugin but the issue wasn't solved, I'm using UE5.2.1 Source

**Comment by ashe23** [comment]
Hi @ehab2001 

Unfortunately, fixup redirectors of main content folder using option in content browser action menu, not always means you fixed them correctly. Check `OutputLog` and if you have message `Could not delete` , that means it some redirectors are not fixed, even though engine didnt show any error messages.

Here is related issue [issue](https://github.com/ashe23/ProjectCleaner/issues/48).

If you using plugin version v2.0.1, it must show asset paths that failed to be fixed, in `OutputLog`, fix those manually and after it should work fine.

Let me know if there is any other problems.

**Comment by ehab2001** [comment]
*your solution works perfectly!* I had for some unknown reason the file
name in UE different from it's name in windows Explorer, I renamed it in
the project folder to match the name in the Editor Content browser , Fixed
up  Redirectors again and Opened the Plugin window back again, and it works
perfectly, *thank you for the Quick and Detailed Response you've saved me a
lot of time i'm really thankful to you and your plugin is very Helpful!*

‫في السبت، 22 يونيو 2024 في 2:58 م تمت كتابة ما يلي بواسطة ‪Ashot
Barkhudaryan‬‏ ***@***.***‬‏>:‬

**Comment by ashe23** [comment]
Happy to help :)
