### ISSUE TITLE
Clean Project sometimes delete my Level Sequence assets.

### ISSUE THREAD

**Issue by AngelAvellaneda** [ashe23/ProjectCleaner#53]
Hello Ashot, sometime when I do Clean Project it deletes my LevelSequence assets when I have excluyed the folders and classes. I think it could be the FixUpRedirectionFolder too but Im not sure.
![image](https://github.com/user-attachments/assets/c4b954b4-818f-48bc-a191-ddd472158b7e)

**Comment by ashe23** [comment]
Hello @AngelAvellaneda 

Did excluded assets number changes after you pressing `CleanProject` button?

**Comment by ashe23** [comment]
Can you check if those `LevelSequences` deleted when you fixup redirectors from Content folder manually, without using plugin?

**Comment by AngelAvellaneda** [comment]
> Hello @AngelAvellaneda
> 
> Did excluded assets number changes after you pressing `CleanProject` button?

I haven't been able to pay attention because it doesn't always happen, I'll keep an eye out

**Comment by ashe23** [comment]
Also are you sure you are not using `TemplateSequences` ? If so they must be specified in exclude classes separately.

**Comment by AngelAvellaneda** [comment]
Helo @ashe23, 
In fact, the error occurs due to the FixUpRedirectionsFolder and I have **solved it by renaming the sequences** and they are no longer deleted when opening ProjectCleaner or when doing Fixup.
